### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by 1chooo** [mako9/auto-stop#1]
Dear @mako9, 
I am very interested in your project. Could you please provide information on how to build this project? Additionally, I would like to know which WatchOS Simulator you are using. Thank you.

Please don't hesitate to send me a direct message. I truly appreciate your response.

Warm Regards,
@1chooo

**Comment by 1chooo** [comment]
This is the scene after building successfully!
<img width="217" alt="Screen Shot 2023-06-19 at 1 29 24 PM" src="https://github.com/mako9/auto-stop/assets/94162591/8734622b-5a52-466e-9d9a-948baa23d6fe">

**Comment by mako9** [comment]
Hey @1chooo, 
thanks for your interest into my little project. This was more like a MVP to test in general if this use case is realizable. So it's in a non-finished work in progress state. If you give me some time I can come back to this project and try to make it work (again).
Cheers! @mako9
